# Generated by Django 3.2.9 on 2022-01-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
